version: 0.2

batch:
  build-matrix:
    dynamic:
      env:
        variables:
          PYTHON_VERSION:
            - "3.9"
            - "3.11"
            - "3.12"

env:
  shell: bash
  variables:
    PROJECT_NAME: "MLOps-Learning"
    AWS_DEFAULT_REGION: "eu-north-1"
    AWS_ACCOUNT_ID: "618951596025"
    IMAGE_REPO_NAME: "mlops-learning-repo"

phases:
  install:
    commands:
      - echo ">>> INSTALL | Python $PYTHON_VERSION"
      - pyenv global $PYTHON_VERSION
      - python --version

      - pip install --upgrade pip
      - pip install uv
      - make install

      # Docker daemon
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo ">>> ECR Login"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
       # IMAGE TAG
      - export GIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - export IMAGE_TAG="py-${PYTHON_VERSION}-${GIT_SHA}"
      - echo "🔥 IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo ">>> FORMAT / LINT / TEST"
      - make format
      - make lint
      - make test
      - echo ">>> Docker build"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG



  post_build:
    commands:
      - echo ">>> Push image"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG


reports:
  pytest_reports:
    files:
      - test-results.xml
    file-format: JUNITXML

cache:
  paths:
    - '/root/.cache/pip'
    - '.venv/**/*'
