version: 0.2

batch:
  build-matrix:
    static:
      ignore-failure: false
    dynamic:
      env:
        variables:
          PYTHON_VERSION:
            - "3.9"
            - "3.11"
            - "3.12"

env:
  shell: bash
  variables:
    PROJECT_NAME: "MLOps-Learning"
    ENV_TYPE: "Staging"

phases:
  install:
    commands:
      - echo ">>>INSTALL Muhit hazirlanir"
      - echo "Secilen Versiya: $PYTHON_VERSION"
      - pyenv global $PYTHON_VERSION
      - echo "Hazirki Python versiyasi $PYTHON_VERSION"
      - pip install uv
      - make install

  build:
    commands:
      - echo "Kod formatlanir"
      - make format
      - echo "LINTERING"
      - make lint
      - echo "TESTING"
      - make test

reports:
  pytest_reports:
    files:
      - test-results.xml
    base-directory: reports
    file-format: JUNITXML

artifacts:
  files:
    - dist/**/*
    - README.md
  name: build-output-$PYTHON_VERSION

cache:
  paths:
    - '/root/.cache/pip'
    - '.venv/**/*'
